version: "3.8"

services:
  leaderpostgres:
    image: postgres:14.13
    container_name: leaderpostgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - leaderpostgres-data:/var/lib/postgresql/data
  leadernode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadernode
    depends_on:
      leaderpostgres:
        condition: service_healthy
    env_file: ./.env
    environment:
      LEADER_PORT: 61280
      NODE_TYPE: leader
      POSTGRES_HOST: "leaderpostgres"
      POSTGRES_PORT: 5432
    volumes:
      - leadernode-key:/app/static-key
    ports:
      - "61280:61280"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 61280"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 2s
  regular1postgres:
    image: postgres:14.13
    container_name: regular1postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: ./.env
    ports:
      - "5433:5432"
    volumes:
      - regular1postgres-data:/var/lib/postgresql/data
  regular2postgres:
    image: postgres:14.13
    container_name: regular2postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: ./.env
    ports:
      - "5434:5432"
    volumes:
      - regular2postgres-data:/var/lib/postgresql/data
  regularnode1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regularnode1
    depends_on:
      leadernode:
        condition: service_healthy
      regular1postgres:
        condition: service_healthy
    ports:
      - "61281:61281"
    env_file: ./.env
    environment:
      LEADER_IP: 127.0.0.1
      LEADER_PORT: 61280
      PORT: 61281
      EOA_PRIVATE_KEY: $EOA_PRIVATE_KEY_1
      NODE_TYPE: regular
      POSTGRES_HOST: "regular1postgres"
      POSTGRES_PORT: 5432
    volumes:
      - regularnode1-key:/app/static-key
  regularnode2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regularnode2
    depends_on:
      leadernode:
        condition: service_healthy
      regular2postgres:
        condition: service_healthy
    ports:
      - "61282:61282"
    env_file: ./.env
    environment:
      LEADER_IP: 127.0.0.1
      LEADER_PORT: 61280
      PORT: 61282
      EOA_PRIVATE_KEY: $EOA_PRIVATE_KEY_2
      NODE_TYPE: regular
      POSTGRES_HOST: "regular2postgres"
      POSTGRES_PORT: 5432
    volumes:
      - regularnode2-key:/app/static-key

volumes:
  leaderpostgres-data:
  regular1postgres-data:
  regular2postgres-data:
  leadernode-key:
  regularnode1-key:
  regularnode2-key:
