version: '3.8'

services:
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drb-node
    environment:
      - CONFIG_BASE_PATH=/root/
    volumes:
      - ./config.json:/root/config.json
      - ./contract/abi/DRBCoordinator.json:/root/contract/abi/DRBCoordinator.json
      - .env:/root/.env
    stdin_open: true
    tty: true
