version: '3.8'

services:
  my-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drb-node
    environment:
      - CONFIG_BASE_PATH=/root/
    volumes:
      - ./config.json:/root/config.json
      - ./contract/abi/CRRNGCoordinatorPoF.json:/root/contract/abi/CRRNGCoordinatorPoF.json
      - .env:/root/.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
